name: Air4Thai PM2.5 Data Crawler

on:
  schedule:
    # ตั้งเวลาให้บอทตื่นมารันออโต้ทุกนาทีที่ 5 ของทุกชั่วโมง
    - cron: '5 * * * *'
  workflow_dispatch: # เปิดปุ่มให้เรากดสั่งรันมือเพื่อทดสอบเองได้

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest

    steps:
    # 1. ดึงโค้ดจากระบบมาใส่คอมจำลอง
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. ติดตั้ง Python เวอร์ชันที่เสถียร
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 3. ติดตั้งไลบรารีที่ต้องใช้ในการเชื่อมต่อ API และ MongoDB
    - name: Install dependencies
      run: |
        pip install requests pymongo dnspython

    # 4. สั่งรันไฟล์ดึงฝุ่น พร้อมแอบดึงรหัสผ่านลับส่งเข้าไปให้ในระบบ
    - name: Run get_pm25_auto.py
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: python "get_pm25_auto.py"
